use ads;
CREATE TABLE IF NOT EXISTS `ads`.`mem_market_tag_datail_record`(
`member_id` int COMMENT '会员ID',
`member_type` string COMMENT '会员类型 P: 手机会员 C: 实体卡会员',
`phone_num` string COMMENT '手机号码',
`wx_open_id` string COMMENT '微信OpenId',
`status` string COMMENT '状态 N：正常 L：挂失 D：注销 S：锁定 U永久锁定',
`member_sex` string COMMENT '会员性别 M：男 F：女',
`account_balance` int COMMENT '最新账户余额',
`integral_account_balance` int COMMENT '最新积分账户余额',
`integral_account_total` int COMMENT '最新积分账户总额',
`growth_value` int COMMENT '成长值',
`wx_binding_status` string COMMENT '微信绑定状态',
`register_time` BIGINT COMMENT '注册日期',
`register_duration` int COMMENT '注册时长',
`member_level_id` int COMMENT '会员等级ID',
`register_store_code` string COMMENT '注册门店代码',
`first_login_store` string COMMENT '首次访问门店代码',
`register_city_code` string COMMENT '注册城市',
`register_org_code` string COMMENT '注册配送中心代码',
`register_channel` string COMMENT '注册渠道代码',
`busi_type` string COMMENT '业务类型 C:消费 D:充值 R:退款 T:三方',
`deal_serial_num` string COMMENT '交易序号',
`deposit_amt` int COMMENT '充值金额',
`refund_amt` int COMMENT '退款金额',
`pay_way` string COMMENT '支付方式',
`consume_store_code` string COMMENT '消费门店代码',
`consume_city_code` string COMMENT '消费城市',
`consume_org_code` string COMMENT '消费配送中心代码',
`consume_channel` string COMMENT '消费渠道代码',
`coupon_name` string COMMENT '优惠券定义名称',
`coupon_batch_num` string COMMENT '优惠券批次',
`consume_amt` int COMMENT '消费金额',
`shop_cycle` int COMMENT '购物周期',
`shop_period` int COMMENT '购物时段',
`refund_time` BIGINT COMMENT '退款日期',
`consume_time` BIGINT COMMENT '消费日期',
`deposit_time` BIGINT COMMENT '充值日期',
`single_integral_value` int COMMENT '单笔积分值',
`single_integral_expire_time` BIGINT COMMENT '单笔积分过期日期',
`single_integral_create_time` BIGINT COMMENT '单笔积分领取日期',
`itemcode` string COMMENT '单品代码',
`itemname` string COMMENT '单品名称',
`middle_type_code` string COMMENT '中类代码',
`small_type_code` string COMMENT '小类代码(消费品类)',
`small_item_name` string COMMENT '小类名称(消费品类)',
`consume_cnt` int COMMENT '消费次数',
`refund_cnt` int COMMENT '退款次数',
`deposit_cnt` int COMMENT '充值次数',
`tpp_consume_cnt` int COMMENT '三方消费次数',
`tpp_delivery_time` BIGINT COMMENT '三方配送日期',
`tpp_payment_time` BIGINT COMMENT '三方消费日期',
`tpp_channel_key` string COMMENT '三方消费渠道',
`tpp_consume_amt` int COMMENT '三方消费金额',
`tpp_store_code` string COMMENT '三方消费门店',
`tpp_city_code` string COMMENT '三方消费城市',
`tpp_org_code` string COMMENT '三方消费配送中心',
`tpp_payment_type` string COMMENT '三方支付方式',
`tpp_payment_way` string COMMENT '三方支付渠道',
`tpp_goods_code` string COMMENT '三方商品编号',
`tpp_goods_name` string COMMENT '三方商品名称'
)
COMMENT '会员模块-营销标签明细记录表'
PARTITIONED BY(part_date string)
ROW FORMAT delimited
FIELDS TERMINATED BY '*'
LINES TERMINATED BY '\n'
STORED AS PARQUET;

CREATE TABLE  IF NOT EXISTS `ads`.`mem_market_tag_sum` (
  `member_id` int COMMENT '会员ID',
  `member_type` string COMMENT '会员类型 P: 手机会员 C: 实体卡会员',
  `phone_num` string COMMENT '手机号码',
  `wx_open_id` string COMMENT '微信OpenId',
  `status` string COMMENT '状态 N：正常 L：挂失 D：注销 S：锁定 U永久锁定',
  `member_sex` string COMMENT '会员性别 M：男 F：女',
  `account_balance` int  COMMENT '最新账户余额',
  `integral_account_balance` int COMMENT '最新积分账户余额',
  `integral_account_total` int COMMENT '最新积分账户总额',
  `growth_value` int  COMMENT '成长值',
  `wx_binding_status` string  COMMENT '微信绑定状态',
  `register_time`  BIGINT COMMENT '注册日期',
  `member_level_id` int COMMENT '会员等级ID',
  `register_store`  string COMMENT '注册门店代码',
  `first_login_store`  string COMMENT '首次访问门店代码',
  `register_city_code`  string COMMENT '注册城市',
  `register_org_code`  string COMMENT '注册配送中心代码',
  `register_channel`  string COMMENT '注册渠道代码',
  `register_duration`   int    COMMENT    '注册时长',
  `total_consume_cnt`  int     COMMENT  '累计消费次数',
  `total_consume_amt`   int      COMMENT  '累计消费金额',
  `last_consume_amt`      int   COMMENT  '最后消费金额',
  `last_consume_duration`  int   COMMENT  '最后消费时长',
  `last_consume_time`   BIGINT   COMMENT  '最后消费日期',
  `last_consume_store_code`  string COMMENT    '最后消费门店',
  `last_consume_city_code`  string   COMMENT   '最后消费城市',
  `eb_total_consume_amt`  int  COMMENT    '电商累计消费金额',
  `eb_total_consume_cnt`  int  COMMENT   '电商累计消费次数',
  `last_3m_shop_cycle`   int   COMMENT     '最近3个月购物周期',
  `last_3m_shop_period`  int  COMMENT       '最近3个月购物时段',
  `last_refund_time`   BIGINT   COMMENT   '最后退款日期',
  `last_refund_amt`   int     COMMENT   '最后退款金额',
  `total_refund_cnt`   int     COMMENT   '累计退款次数',
  `total_refund_amt`    int   COMMENT    '累计退款金额',
  `eb_total_refund_amt`  int  COMMENT     '电商累计退款金额',
  `eb_total_refund_cnt`  int  COMMENT     '电商累计退款次数',
  `total_deposit_amt`    int    COMMENT   '累计充值金额',
  `total_deposit_cnt`  int     COMMENT    '累计充值次数',
  `eb_total_deposit_amt` int  COMMENT     '电商累计充值金额',
  `eb_total_deposit_cnt` int  COMMENT     '电商累计充值次数',
  `last_deposit_amt`    int  COMMENT  '最后充值金额',
  `last_deposit_store_code`  string COMMENT    '最后充值门店',
  `last_deposit_city_code`  string   COMMENT   '最后充值城市',
  `last_consume_channel` string COMMENT  '最后消费渠道',
  `last_deposit_channel` string COMMENT  '最后充值渠道',
  `last_refund_channel` string COMMENT  '最后退款渠道',
  `last_refund_store_code`  string COMMENT    '最后退款门店',
  `last_refund_city_code`   string   COMMENT   '最后退款城市',
  `last_consume_org_code`   string COMMENT '最后消费配送中心代码',
  `last_deposit_org_code`   string COMMENT '最后充值配送中心代码',
  `last_refund_org_code`   string COMMENT '最后退款配送中心代码',
  `tpp_total_consume_cnt`  int     COMMENT  '第三方累计消费次数',
  `tpp_total_consume_amt`   int      COMMENT  '第三方累计消费金额'
  )
COMMENT '会员模块-营销标签汇总表'
PARTITIONED BY(part_date string)
ROW FORMAT delimited
FIELDS TERMINATED BY '*'
LINES TERMINATED BY '\n'
STORED AS PARQUET;